name: Count Lines of Code

on:
    push:
        branches:
            - PHPUnit

jobs:
    lines-of-code:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Dependencies
              run: sudo apt-get update && sudo apt-get install -y curl

            - name: Download and Install Tokei
              run: |
                curl -LO https://github.com/XAMPPRocky/tokei/releases/download/v14.1.0/tokei-v14.1.0-x86_64-unknown-linux-gnu.tar.gz
                tar -xzf tokei-v14.1.0-x86_64-unknown-linux-gnu.tar.gz
                sudo mv tokei /usr/local/bin/

            - name: Generate lines of code count
              run: tokei --output json > lines_of_code.json

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: lines-of-code
                  path: lines_of_code.json
